version: "3"
services:
  apache:
    build: .docker/apache
    working_dir: /var/www/html
    depends_on:
      - php-fpm
      - node
      - mysql
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./public:/var/www/html/public
    networks:
      - backend
    environment:
      - PHP_FPM_IP=php-fpm
  php-cli:
    build: .docker/php-cli
    working_dir: /var/www/html
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
      - ./public:/var/www/html/public
    networks:
      - backend
    environment:
      - DATABASE_URL=mysql://root:password@mysql:3306/resume?serverVersion=8.0.23
    command: bash -c "composer update && make base_data && tail -f /dev/null"
  php-fpm:
    build: .docker/php-fpm
    working_dir: /var/www/html
    depends_on:
      - php-cli
      - node
      - mysql
    volumes:
      - ./:/var/www/html
      - ./public:/var/www/html/public
    networks:
      - backend
      - frontend
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password@mysql:3306/resume?serverVersion=8.0.23
    command: bash -c "php-fpm"
  php-myadmin:
    build: .docker/php-myadmin
    depends_on:
      - mysql
    ports:
      - 8081:80
    networks:
      - backend
    environment:
      - PMA_ARBITRARY=1
  node:
    build: .docker/node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./public:/var/www/html/public
    command: bash -c "yarn install --freeze-lock && yarn watch"
  mysql:
    build: .docker/mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=resume
  redis:
    build: .docker/redis
    networks:
      - backend
networks:
  frontend: {}
  backend: {}